# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://6thsigma.github.io/
baseurl: 
title: Aaron Schuenemann
author: Aaron Schuenemann
description: Personal website and projects
avatar: profile.jpg
email: aschuenemann@gmail.com
github: 6thSigma
twitter: aschuen
linkedin: aaronschuenemann
stackoverflow: users/2339943/6thsigma
#Comment out if you don't want disqus
#disqus: username
google_analytics:


# needed for travis-ci build
exclude: [vendor]
